-- قاعدة بيانات مساعد أولياء أمور ثانوية بحرة الأولى
-- شغّلي هذا الملف في Supabase > SQL Editor

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.questions enable row level security;
alter table public.admins enable row level security;

-- الدالة تتحقق من أن المستخدم الحالي ضمن جدول admins.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admins
    where user_id = auth.uid()
  );
$$;

-- الزوار يستطيعون قراءة الأسئلة المفعلة فقط.
drop policy if exists "public_read_active_questions" on public.questions;
create policy "public_read_active_questions"
on public.questions for select
using (is_active = true);

-- المدير/المديرة المصرح له فقط يستطيع رؤية كل الأسئلة.
drop policy if exists "admins_read_all_questions" on public.questions;
create policy "admins_read_all_questions"
on public.questions for select
to authenticated
using (public.is_admin());

-- المدير/المديرة فقط يستطيع الإضافة والتعديل والحذف.
drop policy if exists "admins_insert_questions" on public.questions;
create policy "admins_insert_questions"
on public.questions for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins_update_questions" on public.questions;
create policy "admins_update_questions"
on public.questions for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins_delete_questions" on public.questions;
create policy "admins_delete_questions"
on public.questions for delete
to authenticated
using (public.is_admin());

-- لا نسمح للزوار بقراءة جدول admins.
drop policy if exists "admins_read_own_admin_record" on public.admins;
create policy "admins_read_own_admin_record"
on public.admins for select
to authenticated
using (user_id = auth.uid());

-- لا نضيف المستخدم الإداري من الموقع.
-- أضيفي user_id يدويًا من SQL Editor بعد إنشاء حسابك.

-- بيانات تجريبية اختيارية:
insert into public.questions (question, answer)
select * from (values
('ما أوقات الدوام المدرسي؟','يتم اعتماد أوقات الدوام وفق التنظيم المعتمد من المدرسة، ويمكن التواصل مع الإدارة للتأكد من آخر تحديث.'),
('كيف أستفسر عن غياب ابنتي؟','يمكن متابعة الحضور والغياب عبر المنصة التعليمية المعتمدة، وفي حال وجود استفسار يمكن التواصل مع المدرسة.'),
('كيف أتواصل مع المدرسة؟','يمكن التواصل مع إدارة ثانوية بحرة الأولى من خلال قنوات التواصل الرسمية المعتمدة لدى المدرسة.'),
('ما إجراءات الانصراف؟','تُطبق إجراءات الانصراف وفق الأنظمة والتعليمات المعتمدة في المدرسة.')
) as v(question,answer)
where not exists (select 1 from public.questions);
